export const LOADING = "LOADING";
export const ERROR = "ERROR";

export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";

export const GET_SINGLE_TASK_SUCCESS = "GET_SINGLE_TASK_SUCCESS";

export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";

export const REMOVE_TASK_SUCCESS = "REMOVE_TASK_SUCCESS";

export const REMOVE_SELECTED_TASKS_SUCCESS = "REMOVE_SELECTED_TASKS_SUCCESS";

export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";

export const CHANGE_TASK_STATUS_SUCCESS = "CHANGE_TASK_STATUS_SUCCESS";